### ISSUE TITLE
people.redhat.com seems to block release-monitoring.org's checks

### ISSUE THREAD

**Issue by jccleaver** [release-monitoring/anitya#836]
Apologies if this isn't the right location for operational issues (vs source issues), but I've noticed that this URL seems to block connections from the project's updates. Perhaps someone on the team can poke someone at RedHat about it?

https://release-monitoring.org/project/21277/

Constantly receives: Could not call : "https://people.redhat.com/~rjones/virt-what/files/" of "virt-what", with error: HTTPSConnectionPool(host='people.redhat.com', port=443): Max retries exceeded with url: /~rjones/virt-what/files/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f124f90f890>: Failed to establish a new connection: [Errno 111] Connection refused'))

...however the configured URLs come up completely fine for me.

**Comment by Zlopez** [comment]
Thanks for the issue.

I looked at the project and it seems to be correctly setup, could you try custom backend, if it helps?

**Comment by jccleaver** [comment]
Modified the entry to custom and I'm still getting the same error.

Based on the message, I presume it's unable to get an HTTP response in the first place, so I'm not sure that the backend would matter.

**Comment by Zlopez** [comment]
I think folder is using urllib3 directly and custom should use requests library.

It's possible that redhat.com is blocking bots and this is causing the issue.

**Comment by jccleaver** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1750539 .. Hopefully dealt with there.

**Comment by Zlopez** [comment]
@jccleaver Thanks for filling the bug

**Comment by jccleaver** [comment]
Poked the BZ, but issue is still present.

**Comment by Zlopez** [comment]
I unfortunately don't have rights to see the issue, so I don't know whats happening.

**Comment by Zlopez** [comment]
@jccleaver Did you get any update for this?

**Comment by jccleaver** [comment]
Someone actively deleted the virt-what project on Anitya that I created (formerly at https://release-monitoring.org/project/21277/ ), which I take to mean there is active disinterest in fixing this.

I created a new virt-what project (https://release-monitoring.org/project/72623/) and it looks like the same issue is still going on. The reported error is:

`Could not call : "https://people.redhat.com/~rjones/virt-what/files/" of "virt-what", with error: HTTPSConnectionPool(host='people.redhat.com', port=443): Max retries exceeded with url: /~rjones/virt-what/files/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd484127c18>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by Zlopez** [comment]
@jccleaver This was deleted by automatic I added in latest release, if the project doesn't have any mapping, it is deleted after 100 retries, if it has mapping and no version, it's still deleted. You can see the number of retries on the project page as `Checks failed`.

There was a huge amount of fake projects created lately, which were never successful in retrieving any version. This is why I implemented this feature and after week it deleted more than 1000 projects without any version.

I'm sorry this also affected your project.

**Comment by bowlofeggs** [comment]
> if it has mapping and no version, it's still deleted.

I have set up Anitya to track projects that don't currently have a release, so that I can get notified if they ever do make a release. This behavior would make that use case impossible.

**Comment by Zlopez** [comment]
@bowlofeggs If they are set up correctly and only don't retrieve any version, than they will not get deleted. Only those that are constantly failing, like responding with error above, are deleted after 100 retries.

**Comment by jccleaver** [comment]
FTR, I just checked and this issue is still present. Perhaps someone at RH can take a look? I'll poke the existing BZ with an update as well.

https://release-monitoring.org/project/369334/

`Fail | 1 | 2023-09-22 19:18:55 (UTC) | Could not call : "https://people.redhat.com/~rjones/virt-what/files/" of "virt-what", with error: HTTPSConnectionPool(host='people.redhat.com', port=443): Max retries exceeded with url: /~rjones/virt-what/files/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdcf662d950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`
